In [1]:
import torch
import torch.nn as nn
import math

In [2]:
def make_Diag_Block(Ab, l, L):
###対角ブロック行列
  def block(a, l, L):
    theta = 2*math.pi*a*l/(L+1)
    return torch.tensor([[math.cos(theta), -math.sin(theta)],
                         [math.sin(theta), math.cos(theta)]])
  Ab = torch.stack((Ab.real, Ab.imag), dim=1).flatten()
  return torch.block_diag(*[block(a, l, L) for a in Ab])

def Kernel_DiagBlock(A, P, Q, B, C, step, L):
  return torch.stack([C @ make_Diag_Block(A, l, L) @ B for l in range(L)])

make_Diag_Block(torch.randn(1, dtype=torch.cfloat), 1, 1)

tensor([[ 0.0625,  0.9980,  0.0000,  0.0000],
        [-0.9980,  0.0625,  0.0000,  0.0000],
        [ 0.0000,  0.0000, -0.9412, -0.3378],
        [ 0.0000,  0.0000,  0.3378, -0.9412]])

In [6]:
from model.ssm import SSM
torch.set_printoptions(precision=3, sci_mode=False)


device = 'cuda'
model = SSM(dim=4, N=16, div=4).to(device)
model(torch.randn(2, 8, 4).to(device), cnn=True).shape

ModuleNotFoundError: No module named 'SSM'

In [4]:
rand = torch.randn(2, 8, 2)
model = SSM(2, 8, div=2)

In [9]:
model(rand, cnn=True)[0]

tensor([[-0.001,  0.005],
        [-0.010,  0.002],
        [ 0.007,  0.094],
        [-0.005,  0.142],
        [-0.017,  0.196],
        [-0.005,  0.216],
        [ 0.008,  0.197],
        [ 0.006,  0.172]], grad_fn=<SelectBackward0>)

In [10]:
model(rand, cnn=False)[0]

tensor([[ 0.011,  0.274],
        [ 0.001,  0.257],
        [ 0.018,  0.335],
        [ 0.006,  0.370],
        [-0.006,  0.411],
        [ 0.006,  0.419],
        [ 0.019,  0.388],
        [ 0.017,  0.352]], grad_fn=<SelectBackward0>)